highlighter: rouge

markdown: kramdown

kramdown:
  input: GFM # The default, can be omitted.
  syntax_highlighter: rouge
  syntax_highlighter_opts: # Rouge Options › https://github.com/jneen/rouge#full-options
    css_class: 'highlight'
  math_engine: mathjax

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed

paginate: 7
paginate_path: "page:num"
layout: post
permalink: /:categories/:title
excerpt_separator: "[-----]"

url: # Required: replace this with your domain
name: unifreak # Required: will be displayed on every page's header
title: unifreak's blog # Required: site's default title
shout: # Required: **TWO** lines, will be displayed on page's header.
  -
  -
description: "unifreak's blog." # Required

disqus:
  comments: false # Global toggle on/off disqus comment
  shortname:  # Required if you use disqus. Replace with your disqus shortname here

gitalk:
  comments: true # Global toggle on/off gitalk comment
  # replace all of those below with your own
  client_id: a9e60308f00d4f50c0a2
  client_secret: af1124f1579da047b071f58a86a9b70c4c172351
  repo: unifreak.github.io
  owner: unifreak
  admin: unifreak
  distraction_free_mode: true

google_analytics:
  id: "G-35QT9DQRZH" # Required if you use google analytics. Replace with your tracking id here

collections: # Define post series here
  book_review:
    output: true
  ref-go:
    output: true
    sort_by: sort

defaults:
  - scope:
      path: ""
    values:
      layout: "post"
